In [15]:
# import packages
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from scipy import signal
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import make_scorer, accuracy_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV


df_training = pd.read_csv('training_data.csv', header=None)
df_testing = pd.read_csv('testing_data.csv', header=None)

y_train = df_training[df_training.shape[1] - 1].values
    # Labels should start from 0 in sklearn
y_train = y_train - 1


y_train = y_train.astype(int)
df_training = df_training.drop([df_training.shape[1] - 1], axis=1)
X_train = df_training.values
print ("training input done ")
y_test = df_testing[df_testing.shape[1] - 1].values
y_test = y_test - 1
y_test = y_test.astype(int)


df_testing = df_testing.drop([df_testing.shape[1] - 1], axis=1)
X_test = df_testing.values
    
print ("testing input done")

# Feature normalization for improving the performance of machine learning models. In this example code, 
    # StandardScaler is used to scale original feature to be centered around zero. You could try other normalization methods.
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

print ("feature normlization done")

 # Build KNN classifier, in this example code
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train, y_train)

    # Evaluation. when we train a machine learning model on training set, we should evaluate its performance on testing set.
    # We could evaluate the model by different metrics. Firstly, we could calculate the classification accuracy. In this example
    # code, when n_neighbors is set to 4, the accuracy achieves 0.757.
y_pred = knn.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))
    # We could use confusion matrix to view the classification for each activity.
print(confusion_matrix(y_test, y_pred))


# Build KNN classifier, in this example code
#tuned_parameters = [{'n_neighbors':[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}]
#acc_scorer = make_scorer(accuracy_score)
#grid_obj  = GridSearchCV(KNeighborsClassifier(), tuned_parameters, cv=10, scoring=acc_scorer)
#grid_obj  = grid_obj .fit(X_train, y_train)
#clf = grid_obj.best_estimator_
#print ("some results")
#print('best clf:', clf)
#clf.fit(X_train, y_train)
#y_pred = clf.predict(X_test)
#print(y_pred)
#print(y_pred.shape, y_test.shape)

#print('Accuracy: ', accuracy_score(y_test, y_pred))
#print(confusion_matrix(y_test, y_pred))
    

training input done 
testing input done
feature normlization done
Accuracy:  0.7504798464491362
[[ 43   3   0   0   0   1   0   0   0   0   7   3   0]
 [  3  54   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3  48   1   2   0   1   0   0   0   1   1   0]
 [  2   0   2  84   4   5   1   1   0   0   0   0   0]
 [  0   0   1   8  36   7   1   3   0   0   1   0   0]
 [  1   1   2  14  26  32   4   1   1   0   1   2   0]
 [  1   0   6   4   2   6 191   4   5   0   0   0   0]
 [  0   0   1   0   0   2  14  21   1   0   0   0   0]
 [  0   0   0   1   0   1   9   2  24   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0  96   0   0   0]
 [  0   0   1   3   2   7   2   0   0   0  58  27   0]
 [  0   0   1   1   0   0   0   0   0   0  39  59   0]
 [  0   0   0   1   0   0   1   0   0   0   0   0  36]]
