In [1]:
# import packages
import numpy as np
import pandas as pd
import math
import matplotlib.pyplot as plt
from scipy import signal
from sklearn import preprocessing
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import make_scorer, accuracy_score, confusion_matrix
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV


df_training = pd.read_csv('training_data.csv', header=None)
df_testing = pd.read_csv('testing_data.csv', header=None)

y_train = df_training[df_training.shape[1] - 1].values
    # Labels should start from 0 in sklearn
y_train = y_train - 1


y_train = y_train.astype(int)
df_training = df_training.drop([df_training.shape[1] - 1], axis=1)
X_train = df_training.values
print ("training input done ")
y_test = df_testing[df_testing.shape[1] - 1].values
y_test = y_test - 1
y_test = y_test.astype(int)


df_testing = df_testing.drop([df_testing.shape[1] - 1], axis=1)
X_test = df_testing.values
    
print ("testing input done")

# Feature normalization for improving the performance of machine learning models. In this example code, 
    # StandardScaler is used to scale original feature to be centered around zero. You could try other normalization methods.
scaler = preprocessing.StandardScaler().fit(X_train)
X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

print ("feature normlization done")


tuned_parameters = [{'kernel': ['rbf'], 'gamma': [1e-1,1e-2, 1e-3, 1e-4],
                 'C': [1e-3, 1e-2, 1e-1, 1, 10, 100, 100]},
                {'kernel': ['linear'], 'C': [1e-3, 1e-2, 1e-1, 1, 10, 100]}]
acc_scorer = make_scorer(accuracy_score)
grid_obj  = GridSearchCV(SVC(), tuned_parameters, cv=10, scoring=acc_scorer)
grid_obj  = grid_obj .fit(X_train, y_train)
clf = grid_obj.best_estimator_
print('best clf:', clf)
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

training input done 
testing input done
feature normlization done
best clf: SVC(C=100, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma=0.01, kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)
Accuracy:  0.710172744721689
[[ 35   3   0   0   0   0   0   0   0   0  16   3   0]
 [  6  51   0   0   0   0   0   0   0   0   0   0   0]
 [  0   3  48   1   1   0   2   0   0   0   1   1   0]
 [  2   0   2  84   6   3   1   0   0   0   0   1   0]
 [  0   0   5   5  36   6   4   0   0   0   0   1   0]
 [  0   1   3   7  27  35   9   0   1   0   0   2   0]
 [  0   0   3   5   1   8 202   0   0   0   0   0   0]
 [  0   0   1   0   0   1  37   0   0   0   0   0   0]
 [  0   0   2   2   0   2  18   0  13   0   1   0   0]
 [  0   0   0   0   0   0   0   0   0  96   0   0   0]
 [  3   0   0   2   0   9   2   0   0   0  70  14   0]
 [  0   0   0   2   0   0   0   0   0   0  64  34   0]
 [  0   0   